name: Run Tests for Module Header Files (Release)

on:
  pull_request:
    branches: [ main ]

jobs:
  header-file-collector:
    runs-on: ubuntu-latest
    name: Get changed header files
    outputs:
      any-header-files: ${{ steps.check-for-header-files.outputs.any-header-files }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get all changed header files
        id: changed-header-files
        uses: tj-actions/changed-files@v42
        with:
          files: |
            **.h

      - name: Check for header files
        id: check-for-header-files
        run: echo "any-header-files=${{ steps.changed-header-files.outputs.any_changed }}" >> $GITHUB_OUTPUT

  test-header-files:
    needs: header-file-collector
    name: Test changed header files
    if: needs.header-file-collector.outputs.any-header-files == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Install googletest
        run: |
          set -e
          sudo apt-get install libgtest-dev
      - uses: actions/checkout@v1

      - name: Configure as Release
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DMODULE_LIST="" ..
        working-directory: ./headers/tests

      - name: Build test project
        run: |
          cmake --build .
        working-directory: ./headers/tests/build

      - name: Execute tests
        run: |
          ctest
          
        working-directory: ./headers/tests/build